package edu.ncsu.csc.CoffeeMaker.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.CoffeeMaker.models.Customer;
import edu.ncsu.csc.CoffeeMaker.models.enums.Role;

/**
 * CustomerRepository is used to provide CRUD operations for the Customer model.
 * Spring will generate appropriate code with JPA.
 *
 * @author Kai Presler-Marshall
 *
 */
public interface CustomerRepository extends JpaRepository<Customer, Long> {

    /**
     * Finds a Customer object with the provided username. Spring will generate
     * code to make this happen.
     *
     * @param username
     *            Username of the Customer
     * @return Found customer, null if none.
     */
    Customer findByUsername ( String username );

    /**
     * Counts the number of customers with the GUEST role.
     *
     * Code generated by ChatGPT
     *
     * @param role
     *            The role to search for (in this case, Role.GUEST).
     * @return The count of customers with the specified role.
     */
    long countByRolesContaining ( Role role );
}
